---
all:
  hosts:
    fs0.medianet:
      ansible_user: root
    dps0.medianet:
      ansible_user: root
    bak0.medianet:
      ansible_user: root
  children:  
    playout:
      hosts:
        playout1.medianet:
          ansible_user: root
        playout2.medianet:
          ansible_user: root
    onair:
      hosts:
        onair1.medianet:
          ansible_user: root
        onair2.medianet:
          ansible_user: root
    log:
      hosts:
        log1.medianet:
          ansible_user: root
        log2.medianet:
          ansible_user: root
    screen:
      hosts:
        screen1.medianet:
          ansible_user: pi
        screen2.medianet:
          ansible_user: pi
        screen3.medianet:
          ansible_user: pi
        screen4.medianet:
          ansible_user: pi        
