---
all:
  hosts:
    raw.medianet:
    fs0.medianet:
    dps0.medianet:
    bak0.medianet:
    digiplay2.medianet:
  children:
    playout:
      hosts:
        playout1.medianet:
        playout2.medianet:
    onair:
      hosts:
        onair1.medianet:
        onair2.medianet:
    log:
      hosts:
        log1.medianet:
        log2.medianet:
    screen:
      hosts:
        screen1.medianet:
        screen2.medianet:
        screen3.medianet:
        screen4.medianet:
