---
- hosts: playout
  roles:
    - autologin_user
- hosts: onair
  roles:
    - onair
- hosts: playout:digiplay2.medianet:fs0.medianet:raw.medianet
  roles:
    - digiplay_mount
- hosts: all
  roles:
    - common
