---

- name: ensure systemd directory exists
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory
- name: ensure service file created
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
- name: ensure service is enabled
  systemd:
    daemon-reload: yes
    enabled: yes
    name: getty@tty1.service
- name: ensure NAutoVTs=1 in logind.conf
  replace:
    path: /etc/systemd/logind.conf
    regexp: '#NAutoVTs=6'
    replace: 'NAutoVTs=1'

