---
- name: ensure pip is installed
  apt:
    name: python-pip
    state: latest
- name: ensure docker pip installed
  pip:
    name: docker
    state: latest
- name: ensure modular-status env file exists
  template:
    src: modular_status.env.j2
    dest: /etc/modular_status.env
- name: ensure modular-status container is running
  docker_container:
    name: modular_status
    image: "raw1251am/modular-status:latest"
    state: started
    env_file: /etc/modular_status.env
    restart_policy: always
    exposed_ports:
      - 8080
