---
- name: ensure pip is installed
  apt:
    name: python-pip
    state: latest
- name: ensure docker pip installed
  pip:
    name: docker
    state: latest
- name: ensure modular-status env file exists
  template:
    src: modular_status.env.j2
    dest: /etc/modular_status.env
- name: ensure modular-status container is running
  docker_container:
    name: modular_status
    image: "raw1251am/modular-status:latest"
    state: started
    env_file: /etc/modular_status.env
    restart_policy: always
    published_ports:
      - "8080:8080"
- name: ensure websockify config updated
  template:
    src: websockify.config.j2
    dest: /etc/websockify.config
- name: ensure websockify container started
  docker_container:
    name: websockify
    image: "efrecon/websockify:latest"
    command: ["80", "--token-plugin", "TokenFile", "--token-source", "/opt/websockify/config"]
    state: started
    restart_policy: always
    published_ports:
      - "3000:80"
    volumes:
      - /etc/websockify.conf:/opt/websockify/config